version: '3.8'
services:
  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/ordersdb
    depends_on:
      - mongo
    networks:
      - app-network  # ✅ Add network

  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/paymentsdb
    depends_on:
      - mongo
    networks:
      - app-network  # ✅ Add network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network  # ✅ Add network

volumes:
  mongo-data:

networks:
  app-network:  # ✅ Define the network
    driver: bridge
